### PR TITLE
WIP: new assertion tests for Dec 2018 testfest

### PR DESCRIPTION
**Pull request by mmccool**
PR for new AssertionTest schemas.   I will be adding to this over the next day or so...
Note: this also merges in the updated TD JSON Schema.
I also updated .gitignore to clean up how empty Results directories are handled.

### CODE REVIEW

**Comment by mmccool** [comment]
BTW I'm not convinced the td-version JSON Schema test is correct.   The TD spec says the following for this assertion:
```
The version container MAY be used to provide additional application and/or device specific version information based on terms from non-TD namespaces.
```
but the description in the AssertionTest schema says
```
The mandatory vocabulary term as defined in the class Versioning, MUST be serialized as a JSON name.
```
which is something completely different.   Not only that, but version is an object, NOT a name.   Probably this schema is just based on an old version of the TD spec...

**Comment by mmccool** [comment]
So it turns out the assertions for properties and events mention that the values of "required" and "enum" should be serialized as arrays but there are no specifications for this in the master JSON Schema, which is probably a bug in the schema.  The assertion for td-actions-events does not mention these but I suspect that is a bug in the assertion.  I wrote some assertion tests for these following the (probably incorrect...) master JSON schema but we will have to fix these later.  I took notes of these issues in the testspec for these assertions.

Sigh.  Nothing is ever easy...

**Comment by mmccool** [comment]
I guess I should create issues for these as I go in wot-thing-description so we can discuss them at the TD meeting on Friday.

**Comment by mmccool** [comment]
One other thing I don't yet understand; how "required" maps onto "not-impl" when there is more than one item.  For example, for td-property-arrays there are several things that, if they appear need to be serialized as arrays.   But not all TDs will have all of these features at the same time.    What we may need to do is create several "child" assertions, one for each specific feature, which then passes or fails (if it appears) or is not-impl if it does not.  Then we can combine them externally.   Then we have to figure out how to "count" the passes or fails; probably a minimum is the way to combine them (since we need a minimum of two implementations to support each feature, so if we see two "passes" on a parent feature a minimum rule to combine results from children would mean we have at least two passes for every child...)

**Comment by mmccool** [comment]
So I checked in a few additional schemas as a basis for discussion:
* `td-property-arrays:forms` is an example of a "child" schema.  We can add a bunch of these whenever we have an assertion that is too hard to express in a single schema, and I can merge them later.
* `td-property-objects` removes one of the "required" elements so it now passes on my test schema that has both property objects and plain types.   However, it ALSO passes when there are NO "properties" objects, so it is probably not what we want.

**Comment by mmccool** [comment]
See also my comment on this issue: https://github.com/w3c/wot-thing-description/issues/322
It looks like readOnly and writeOnly were only very recently (after the testfest-1 tag) made optional.  But this was a bug since they have default values, which is meaningless if they are mandatory.  Anyhow, the schema marks these as "required" but this is wrong.  Do we fix this now or later?

**Comment by mmccool** [comment]
To resolve the issue with td-property-objects I realized that in order to distinguish not-impl from pass we need a way to figure out if a given part of the schema had "matched" or not.  I looked into the docs for avj and found the "$comment" keyword, which seems to do what we want; it calls a function when a given part of the schema is triggered.   I added a prototype example in the td-property-objects.json schema and updated assertionTest.js to log it to the console (for now).  Later I will have to update the not-impl rule to check if the comment was triggered.   But first, there is another annoying bug where the output seems to be non-deterministic... quite annoying.

Also using this will mean getting rid of the unnecessary "required" clauses.  On the other hand, we may be able to just annotate a single large schema rather than having a whole bunch of small ones.

**Comment by mmccool** [comment]
BTW comment on that commit should have been "track matching of rule using $comment" but I forgot about shell variable substitution...

**Comment by yamagile** [comment]
@mmccool and @egekorkan,  
Could you change the json file name "AssertionTester/Assertions/td-property-arrays:forms.json" to another one without ":"? (Windows cannot handle the file name with ":".)

**Pull request merged**
